### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by KaustubhBadrike-GEP** [integrations/microsoft-teams#18]
Option "[Upload a custom app](https://github.com/integrations/microsoft-teams/raw/master/images/Uploadmanifest.png)" is not available

![image](https://user-images.githubusercontent.com/53936855/92027391-1a3ca400-ed80-11ea-989a-f50958a5a102.png)

**Comment by ashokirla** [comment]
@KaustubhBadrike-GEP This could be because you organization has turned off ability to install custom app. You might have to contact your account admin for getting it installed. 

But, I would recommend to wait for couple of days as we are about to release public preview of the app. After that you should be able to install the app from app store directly.
